#!/bin/sh
set -e
set -x

docker build --tag=oak .
docker run \
  --interactive \
  --tty \
  --volume=$PWD/bazel-cache:/root/.cache/bazel \
  --volume=$PWD:/opt/my-project \
  --workdir=/opt/my-project \
  --publish=9999:9999 \
  --publish=30000:30000 \
  oak:latest \
  "$@"
